import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanStackQueryWrapper from "./(components)/TanstackQueryWrapper";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zania - Drag N Drop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <TanStackQueryWrapper>
          <MantineProvider forceColorScheme="dark">
            <Notifications position="bottom-center" />
            {children}
          </MantineProvider>
        </TanStackQueryWrapper>
      </body>
    </html>
  );
}
